export const EMOTIONS = {
  joy: {
    id: 'joy',
    name: 'Joy',
    emoji: '😊',
    colorName: 'Yellow',
    bgLight: 'bg-amber-500/10',
    bgDark: 'dark:bg-amber-500/15',
    borderLight: 'border-amber-400/40',
    borderDark: 'dark:border-amber-500/30',
    textLight: 'text-amber-700',
    textDark: 'dark:text-amber-300',
    glowColor: 'rgba(234, 179, 8, 0.4)',
    progressBg: 'bg-amber-500',
    gradient: 'from-amber-400 to-yellow-500',
    accentHex: '#eab308',
    description: 'Feelings of happiness, delight, celebration, contentment, and positive energy.',
    keywords: ['happy', 'delighted', 'excited', 'thrilled', 'content', 'great', 'awesome', 'smiling']
  },
  love: {
    id: 'love',
    name: 'Love',
    emoji: '❤️',
    colorName: 'Pink',
    bgLight: 'bg-pink-500/10',
    bgDark: 'dark:bg-pink-500/15',
    borderLight: 'border-pink-400/40',
    borderDark: 'dark:border-pink-500/30',
    textLight: 'text-pink-700',
    textDark: 'dark:text-pink-300',
    glowColor: 'rgba(236, 72, 153, 0.4)',
    progressBg: 'bg-pink-500',
    gradient: 'from-pink-400 to-rose-500',
    accentHex: '#ec4899',
    description: 'Affection, deep warmth, romantic admiration, tenderness, and emotional connection.',
    keywords: ['adore', 'cherish', 'affection', 'caring', 'sweetheart', 'beloved', 'heartfelt']
  },
  sadness: {
    id: 'sadness',
    name: 'Sadness',
    emoji: '😢',
    colorName: 'Blue',
    bgLight: 'bg-blue-500/10',
    bgDark: 'dark:bg-blue-500/15',
    borderLight: 'border-blue-400/40',
    borderDark: 'dark:border-blue-500/30',
    textLight: 'text-blue-700',
    textDark: 'dark:text-blue-300',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    progressBg: 'bg-blue-500',
    gradient: 'from-blue-400 to-cyan-500',
    accentHex: '#3b82f6',
    description: 'Sorrow, grief, disappointment, loneliness, melancholy, or heavy emotional distress.',
    keywords: ['depressed', 'lonely', 'miserable', 'heartbroken', 'unhappy', 'crying', 'hopeless']
  },
  fear: {
    id: 'fear',
    name: 'Fear',
    emoji: '😨',
    colorName: 'Purple',
    bgLight: 'bg-purple-500/10',
    bgDark: 'dark:bg-purple-500/15',
    borderLight: 'border-purple-400/40',
    borderDark: 'dark:border-purple-500/30',
    textLight: 'text-purple-700',
    textDark: 'dark:text-purple-300',
    glowColor: 'rgba(168, 85, 247, 0.4)',
    progressBg: 'bg-purple-500',
    gradient: 'from-purple-500 to-indigo-600',
    accentHex: '#a855f7',
    description: 'Anxiety, apprehension, panic, dread, insecurity, or perceived danger.',
    keywords: ['scared', 'terrified', 'anxious', 'panicked', 'worried', 'nervous', 'frightened']
  },
  anger: {
    id: 'anger',
    name: 'Anger',
    emoji: '😠',
    colorName: 'Red',
    bgLight: 'bg-red-500/10',
    bgDark: 'dark:bg-red-500/15',
    borderLight: 'border-red-400/40',
    borderDark: 'dark:border-red-500/30',
    textLight: 'text-red-700',
    textDark: 'dark:text-red-300',
    glowColor: 'rgba(239, 68, 68, 0.4)',
    progressBg: 'bg-red-500',
    gradient: 'from-red-500 to-orange-600',
    accentHex: '#ef4444',
    description: 'Irritation, rage, resentment, frustration, indignation, or intense hostility.',
    keywords: ['furious', 'mad', 'outraged', 'irritated', 'annoyed', 'enraged', 'grouchy']
  },
  surprise: {
    id: 'surprise',
    name: 'Surprise',
    emoji: '😲',
    colorName: 'Green',
    bgLight: 'bg-emerald-500/10',
    bgDark: 'dark:bg-emerald-500/15',
    borderLight: 'border-emerald-400/40',
    borderDark: 'dark:border-emerald-500/30',
    textLight: 'text-emerald-700',
    textDark: 'dark:text-emerald-300',
    glowColor: 'rgba(34, 197, 94, 0.4)',
    progressBg: 'bg-emerald-500',
    gradient: 'from-emerald-400 to-teal-500',
    accentHex: '#22c55e',
    description: 'Astonishment, unexpected shock, wonder, disbelief, or sudden realization.',
    keywords: ['astonished', 'shocked', 'stunned', 'amazed', 'unexpected', 'speechless']
  }
};

export const SAMPLE_TEXTS = [
  { text: "I am feeling very happy and excited about our new project launch today!", emotion: "joy" },
  { text: "I cherish every moment spent with my family, they mean the world to me.", emotion: "love" },
  { text: "I feel so hopeless and sad after hearing the devastating news.", emotion: "sadness" },
  { text: "I am terrified of what might happen during the upcoming emergency drill.", emotion: "fear" },
  { text: "I am feeling extremely grouchy and furious at the rude service.", emotion: "anger" },
  { text: "I was completely stunned and amazed by the unexpected surprise party!", emotion: "surprise" }
];
